version: '2'

services:
    db:
        image: postgres:11.2
        restart: always
        volumes:
            - ./docker/.data/db:/var/lib/postgresql/data
        environment:
            POSTGRES_DB: ${POSTGRES_DB}
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        ports:
            - ${POSTGRES_HOST_PORT}:5432

    php:
        build:
            context: ./docker/php7-fpm
            args:
                TIMEZONE: ${TIMEZONE}
        environment:
            XDEBUG_CONFIG: remote_host=host.docker.internal remote_enable=1 remote_port=9000
            PHP_IDE_CONFIG: serverName=task-area.api.local
            COMPOSER_MEMORY_LIMIT: -1
        volumes:
            - ./:/var/www/api
            - ./docker/php7-fpm/logs:/var/www/api/var/log/php
            - ./docker/php7-fpm/local.ini:/usr/local/etc/php/conf.d/local.ini

    nginx:
        build:
            context: ./docker/nginx
        ports:
            - ${NGINX_HOST_PORT}:80
        volumes_from:
            - php
        volumes:
            - ./docker/nginx/logs/:/var/www/api/var/log/nginx
        depends_on:
            - php
            - db

    db-test:
        image: postgres:11.2
        restart: always
        volumes:
            - ./docker/.data/db-test:/var/lib/postgresql-test/data
        environment:
            POSTGRES_DB: 'api_test'
            POSTGRES_USER: 'api_test'
            POSTGRES_PASSWORD: 'api_test'
        ports:
            - 5433:5432
